# DataFrame
- 행열을 가진 2차원 자료구조
- 여러개의 Series 묶음 자료형

In [65]:
import numpy as np
import pandas as pd
from fontTools.misc.plistlib import Data

## DataFrame 생성

In [66]:
# dict -> df 생성
data = {"one": [1.0, 2.0, 3.0], "two": [10, 20, 30], "three": 99}

# dict 의 각 item이 하나의 series로 처리됨
df = pd.DataFrame(data) # 차수가 다르면 자동으로 값이 채워지는 브로드캐스팅 발생
print(df['one']) # 'one'열의 Series 선택
df

0    1.0
1    2.0
2    3.0
Name: one, dtype: float64

   one  two  three
0  1.0   10     99
1  2.0   20     99
2  3.0   30     99

In [67]:
# 여러 개의 dict -> dataframe
data : list[dict[str,int]] = [{
    "a": 10,
    "b": 20,
}, {
    "a": 30,
    "b": 40,
    "c": 50,
}]

# 하나의 dict -> 하나의 레코드, key는 컬럼으로 처리
df = pd.DataFrame(data)
df # 0 번행의 C 열의 NaN == 결측치

    a   b     c
0  10  20   NaN
1  30  40  50.0

In [68]:
# ndarray -> df
# 컬럼이름, 인덱스 이름 라벨링
arr = np.arange(9).reshape(3,3)
df = pd.DataFrame(arr, columns=('a','b','c'), index = ['1일','2일','3일'])
df

    a  b  c
1일  0  1  2
2일  3  4  5
3일  6  7  8

In [69]:
# ser -> df 시리즈로 데이터프레임 만들기
#시리즈를 두개 만든 다음에 키 값을 넣어서 딕셔너리 만들기
name_ser = pd.Series(["홍길동", "이순신", "강감찬"])
age_ser = pd.Series([20, 25, 30])

df = pd.DataFrame({"name": name_ser, "age": age_ser})
df

  name  age
0  홍길동   20
1  이순신   25
2  강감찬   30

In [70]:
# tuple(record) -> dataframe
# 하나의 객체

data = [
    ('홍길동', 20),
    ('이순신', 30),
    ('논개', 43),
]
df = pd.DataFrame.from_records(data, columns=['이름', '나이'])
df

    이름  나이
0  홍길동  20
1  이순신  30
2   논개  43

## DataFrame 속성

In [71]:
data = {
    'Bank client ID':[1, 2, 3, 4],
    'Bank Client Name':['Laila Aly', 'Kate Steve', 'Nicole Mitch', 'Francis Morris'],
    'Net worth [$]':[35000, 3000, 100000, 2000],
    'Years with bank':[4, 7, 10, 15]
}
df = pd.DataFrame(data)
df

   Bank client ID Bank Client Name  Net worth [$]  Years with bank
0               1        Laila Aly          35000                4
1               2       Kate Steve           3000                7
2               3     Nicole Mitch         100000               10
3               4   Francis Morris           2000               15

In [72]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Bank client ID    4 non-null      int64
 1   Bank Client Name  4 non-null      str
 2   Net worth [$]     4 non-null      int64
 3   Years with bank   4 non-null      int64
dtypes: int64(3), str(1)
memory usage: 305.0 bytes

In [73]:
df.describe() # df 설명

       Bank client ID  Net worth [$]  Years with bank
count        4.000000       4.000000         4.000000
mean         2.500000   35000.000000         9.000000
std          1.290994   45963.753836         4.690416
min          1.000000    2000.000000         4.000000
25%          1.750000    2750.000000         6.250000
50%          2.500000   19000.000000         8.500000
75%          3.250000   51250.000000        11.250000
max          4.000000  100000.000000        15.000000

In [74]:
print(df.index)
print(df.columns)

RangeIndex(start=0, stop=4, step=1)
Index(['Bank client ID', 'Bank Client Name', 'Net worth [$]',
       'Years with bank'],
      dtype='str')

In [75]:
print(df.dtypes)
print(df.shape)
print(df.size)

Bank client ID      int64
Bank Client Name      str
Net worth [$]       int64
Years with bank     int64
dtype: object
(4, 4)
16

## DataFrame 메서드

In [76]:
# head(n), tail(n): 맨 위/ 밑 n 개 조회
display(df.head(2))
display(df.tail(2))
# display : 두개 df 동시에 보여줌

   Bank client ID Bank Client Name  Net worth [$]  Years with bank
0               1        Laila Aly          35000                4
1               2       Kate Steve           3000                7

   Bank client ID Bank Client Name  Net worth [$]  Years with bank
2               3     Nicole Mitch         100000               10
3               4   Francis Morris           2000               15

In [77]:
# values_counts(): 유일값 분포 확인
df['Years with bank'].value_counts()

Years with bank
4     1
7     1
10    1
15    1
Name: count, dtype: int64

In [78]:
df

   Bank client ID Bank Client Name  Net worth [$]  Years with bank
0               1        Laila Aly          35000                4
1               2       Kate Steve           3000                7
2               3     Nicole Mitch         100000               10
3               4   Francis Morris           2000               15

In [79]:
# bank client ID가 PK역할을 하므로
# index 재지정: 특정 컬럼을 index 지정
df = df.set_index("Bank client ID")
df

               Bank Client Name  Net worth [$]  Years with bank
Bank client ID
1                     Laila Aly          35000                4
2                    Kate Steve           3000                7
3                  Nicole Mitch         100000               10
4                Francis Morris           2000               15

## 조회
- 행열조회
    - df.iloc[인덱스]
    - df.loc[라벨]
- 열조회
    - df[컬럼명]

In [80]:
dicts = [
    {'name' : '홍길동', 'job' : '강사', 'age' : 33},
    {'name' : '신사임당', 'age' : 44, 'job' : '영업사원'},
    {'name' : '이순신', 'age' : 38, 'job' : '장군'},
    {'name' : '논개', 'age' : 25, 'job' : '개발'},
    {'name' : '강감찬', 'age' : 47, 'job' : '교수'},
]
df = pd.DataFrame(dicts)
df

   name   job  age
0   홍길동    강사   33
1  신사임당  영업사원   44
2   이순신    장군   38
3    논개    개발   25
4   강감찬    교수   47

### iloc (인덱스 위치)

In [81]:
# 홍길동 행 조회
print(df.iloc[0])
print()
print(type(df.iloc[0])) # Series, df에서 한 행 또는 한 열은 Series 타입니다.
print()
print(df.iloc[0].index)
print()
print(df.iloc[0].name) # df의 인덱스 == ser 의 이름

name    홍길동
job      강사
age      33
Name: 0, dtype: object

<class 'pandas.Series'>

Index(['name', 'job', 'age'], dtype='str')

0

In [82]:
# 슬라이싱 지원
df2 = df.iloc[0:2] # 0,1 행 반환
df2

   name   job  age
0   홍길동    강사   33
1  신사임당  영업사원   44

In [83]:
# fancy indexing    지원
df.iloc[[0,2]]

  name job  age
0  홍길동  강사   33
2  이순신  장군   38

In [84]:
# 단일 값 조회
print(df.iloc[0,1])

# 여러 열 조회
df.iloc[:2, 1]

강사

0      강사
1    영업사원
Name: job, dtype: str

In [85]:
df.iloc[:2, :2] # 0-1번행, 0-1범열
print(type(df2))
df2

<class 'pandas.DataFrame'>

   name   job  age
0   홍길동    강사   33
1  신사임당  영업사원   44

### loc
인데스라벨을 통해 조회

In [86]:
# 인덱스에 대입, 인덱스명 지정 == 라벨링
df.index = ['client1', 'client2', 'client3', 'client4', 'client5']
df

         name   job  age
client1   홍길동    강사   33
client2  신사임당  영업사원   44
client3   이순신    장군   38
client4    논개    개발   25
client5   강감찬    교수   47

In [87]:
print(type(df.loc['client4'])) # Series type
df.loc['client4']

<class 'pandas.Series'>

name    논개
job     개발
age     25
Name: client4, dtype: object

In [88]:
# df.loc[3] # 인덱스가 바뀌어서 안됨. KeyError
df.iloc[3] # 그대로

name    논개
job     개발
age     25
Name: client4, dtype: object

## loc 슬라이싱은 end 값을 포함한다

In [89]:
# loc 를 이용한 컬럼 단일 값 조회
print(df.loc['client2', 'job'])

# loc를 이용한 슬라이싱
print(df.loc['client2':'client4'])
print()

# loc를 이용한 슬라이싱 + 컬럼 선택 - client 2,3,4,행의 job만 보기
print(df.loc['client2':'client4', 'job'])
print()


# loc를 이용한 슬라이싱 + 컬럼 선택 - client 2,3,4,행의 job + age보기
print(df.loc['client2':'client4', 'job':])
print()

영업사원
         name   job  age
client2  신사임당  영업사원   44
client3   이순신    장군   38
client4    논개    개발   25

client2    영업사원
client3      장군
client4      개발
Name: job, dtype: str

          job  age
client2  영업사원   44
client3    장군   38
client4    개발   25

### 컬럼라벨

In [90]:
# df['컬럼명'] : 해당 컬럼 시리즈 반환
print(type(df['name'])) # 가로든 세로든 한 줄이면 시리즈임.
df['name']

<class 'pandas.Series'>

client1     홍길동
client2    신사임당
client3     이순신
client4      논개
client5     강감찬
Name: name, dtype: str

In [91]:
# 컬러라벨 fancy indexing
print(type(df[['name', 'job']] ))
df[['name', 'job']] # 한줄이 아니다 -> 시리즈의 묶음 : dataframe 타입

<class 'pandas.DataFrame'>

         name   job
client1   홍길동    강사
client2  신사임당  영업사원
client3   이순신    장군
client4    논개    개발
client5   강감찬    교수

In [92]:
# loc + 컬럼라벨( boolean indexing)
print(df['name'] == '이순신') # 불리언인덱싱
print()
print(df.loc[df['name'] == '이순신']) # 팬시 인덱싱

client1    False
client2    False
client3     True
client4    False
client5    False
Name: name, dtype: bool

        name job  age
client3  이순신  장군   38

In [93]:
# boolean indexing (비교연산)
print(df['age'] > 30)
df[df['age'] > 30]

client1     True
client2     True
client3     True
client4    False
client5     True
Name: age, dtype: bool

         name   job  age
client1   홍길동    강사   33
client2  신사임당  영업사원   44
client3   이순신    장군   38
client5   강감찬    교수   47

In [94]:
# 30세 미만, 개발 직종을 갖는 행 조회
df.loc[ ( df['age'] < 30 ) & ( df['job'] == '개발' ) ]

        name job  age
client4   논개  개발   25

In [95]:
# - 이름에 '신'이 들어가거나 나이가 40대이상 조회
df[(df['age'] >= 40) | (df['name'].str.contains('신'))]

         name   job  age
client2  신사임당  영업사원   44
client3   이순신    장군   38
client5   강감찬    교수   47

## 행 추가/삭제

In [96]:
students = [
    {'name': '홍길동', 'midterm': 95, 'final': 85},
    {'name': '신사임당', 'midterm': 85, 'final': 80},
    {'name': '이순신', 'midterm': 10, 'final': 30}
]
df = pd.DataFrame(students)
df

   name  midterm  final
0   홍길동       95     85
1  신사임당       85     80
2   이순신       10     30

In [108]:
# 중복되니 않는 인덱스에 한 행(Series타입) 추가(대입)
next_index = len(df)

df.loc[next_index] = pd.Series({'name': '강감찬', 'midterm': 88})  # 추가된 행에 final컬럼값 누락 -> NaN (결측치)
df

   name  midterm  final
0   홍길동     95.0   85.0
1  신사임당     85.0   80.0
2   이순신     10.0   30.0
3   강감찬     88.0    NaN

In [112]:
# 중복되는 인덱스에 값 추가 = 대체됨
next_index = 3

df.loc[next_index] = pd.Series({'name': '율곡이이', 'midterm': 77})  # 추가된 행에 final컬럼값 누락 -> NaN (결측치)
df

   name  midterm  final
0   홍길동     95.0   85.0
1  신사임당     85.0   80.0
2   이순신     10.0   30.0
3  율곡이이     77.0    NaN

In [114]:
# 행삭제 -> 원본 유지
# display( df.drop(3)
# display(df)
df = df.drop(3)
df

   name  midterm  final
0   홍길동     95.0   85.0
1  신사임당     85.0   80.0
2   이순신     10.0   30.0

In [ ]:
df.loc[:, 'phone'] = ['010-1234-5678', ['010-3333-4444']]
df

In [116]:
# 특정 조건을 만족하는 모든 행 삭제
df = df[df['final'] >= 60 ] # 60점 이상만 남기기 == 60점 미만 삭제
df

   name  midterm  final
0   홍길동     95.0   85.0
1  신사임당     85.0   80.0

## 컬럼 추가/삭제

In [ ]:
# 중간고사, 기말고사 평균 컬럼(mean)을 추가
df.loc[:, 'mean'] = (df['midterm'] + df['final']) / 2
df

In [ ]:
# 컬럼삭제
df[['name', 'midterm', 'final']] # fancy indexing

In [ ]:
def pass_or_fail(value):
    return 'P' if value >= 60 else ('F')

df.loc[:, 'avg'] = (df['midterm'] + df['final']) / 2

df.loc[:, 'pass_fail'] = df['avg'].apply(pass_or_fail)
df

In [117]:
# apply 함수에 행 (record) 전체를 인자로 전달해서 처리하기
def pass_or_fail2(record):
    avg = (record['midterm'] + record['final']) / 2
    return 'P' if avg >= 60 else 'F'

df.loc[:, 'pass_fail2'] = df.apply(pass_or_fail2, axis = 1)

## 정렬

In [ ]:
# 순위 부여하기
df.loc[:, 'Net Worth Rank'] = df['Net Worth'].rank(ascending=False).astype(int)
df.sort_values('Net Worth Rank')